### PR TITLE
update due to my test.

### PR DESCRIPTION
**Pull request by zhangn1985**

### CODE REVIEW

**Comment by zhangn1985** [comment]
@numbqq that's good to know.

**Comment by zhangn1985** [comment]
@numbqq only binaries release, what about source, or header file? XXX-dev package?

**Comment by numbqq** [comment]
Hello zhangn1985,

I don't want to add the source code to fenix, becase I want to reduce the build time and make it easy to use.

By the way, can you kindly modify your PR? So that I can merge this commit https://github.com/khadas/fenix/pull/8/commits/64304036daf5558202c232386cbb4073bf3e62aa

Thanks.

**Comment by zhangn1985** [comment]
OK,  I will close it and submit new PR.

**Pull request closed without merging**
