### PR TITLE
add `sudo` to lsmod invocation

### PR DESCRIPTION
**Pull request by kostousov-ds**
fix issue #35

### CODE REVIEW

**Comment by numbqq** [comment]
Hello @kostousov-ds

Thanks for your PR.

I will test your patches...

**Comment by kostousov-ds** [comment]
hm... commad `modprobe -q binfmt_misc` should be executed outside of docker

**Comment by numbqq** [comment]
Hello @kostousov-ds 

You don't need to add `sudo` to execute the commands. because these script will be wxecuted with `sudo`.

**Comment by kostousov-ds** [comment]
Hm... Can you test docker on fedora live?
I tried any different variants and it worked only with sudo for losetup and changed docker run command

**Comment by numbqq** [comment]
Hello @kostousov-ds 

OK. We will test on fedora.

**Comment by wangyanbiao518** [comment]
> Hm... Can you test docker on fedora live?
> I tried any different variants and it worked only with sudo for losetup and changed docker run command



> Hm... Can you test docker on fedora live?
> I tried any different variants and it worked only with sudo for losetup and changed docker run command

Hello,I try it with fedora 30 server,But I had a problem with `rsync : rsync_xal_set: lsetxattr`.So can you tell me whcih fedora you used ? with virtual Box ? or host ?

**Comment by kostousov-ds** [comment]
I built an image on fedora 30 host (on my laptop)

xian dan auto man <notifications@github.com> 9 мая 2019 г. 3:54:58 PM написал:

**Comment by wangyanbiao518** [comment]
Hi @kostousov-ds  ,I test it with fedora.THis is my step:
1.diable SELinux
2.```
mount -o loop "${IMAGE_LOOP_DEV_ROOTFS}" $ROOTFS
+               mount "${IMAGE_LOOP_DEV_ROOTFS}" $ROOTFS
 mount -o loop "${IMAGE_LOOP_DEV_BOOT}" $ROOTFS/boot
+               mount "${IMAGE_LOOP_DEV_BOOT}" $ROOTFS/boot
```
I don't add `sudo` to anywhere.And I seccess to build in docker .
Can you test with my step? Thanks.

**Comment by numbqq** [comment]
Hello @kostousov-ds 

As @wangyanbiao518 tested, you don't need to add `sudo` to script on `Fedora`, you just need to diable SELinux, I don't want to merge the patch witch add `sudo`, so I will cherry-pick `fix mount loop device problems` and `
update docker run command to fix loop devices problem` manually.

**Pull request closed without merging**
